name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  WEBVIEW2_VERSION: 1.0.1901.177

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            name: macos
            cmake_args: ""

          - os: windows-latest
            name: windows-64bit
            cmake_args: -G "Visual Studio 17 2022" -A x64 -D"JUCE_WEBVIEW2_PACKAGE_LOCATION=$env:LOCALAPPDATA\NuGet\Cache"
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Install WebView2 via NuGet (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          nuget install Microsoft.Web.WebView2 -Version ${{ env.WEBVIEW2_VERSION }} -OutputDirectory $env:LOCALAPPDATA/NuGet/Cache
          
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release ${{ matrix.cmake_args }}
          cmake --build build --config Release --target WebViewPlugin_VST3 --parallel 4